ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passwordMustChange" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "PayoutAccount" ADD COLUMN IF NOT EXISTS "legalName" TEXT;
ALTER TABLE "PayoutAccount" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "PayoutAccount" ADD COLUMN IF NOT EXISTS "contactEmail" TEXT;
ALTER TABLE "PayoutAccount" ADD COLUMN IF NOT EXISTS "taxId" TEXT;
ALTER TABLE "PayoutAccount" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "PayoutAccount" ADD COLUMN IF NOT EXISTS "branchName" TEXT;
ALTER TABLE "PayoutAccount" ADD COLUMN IF NOT EXISTS "accountType" TEXT;
ALTER TABLE "PayoutAccount" ADD COLUMN IF NOT EXISTS "payoutMethod" TEXT NOT NULL DEFAULT 'BANK_TRANSFER';
ALTER TABLE "PayoutAccount" ADD COLUMN IF NOT EXISTS "promptpayType" TEXT;
ALTER TABLE "PayoutAccount" ADD COLUMN IF NOT EXISTS "note" TEXT;
